version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: no
    ports:
      - "8081:8081"
    networks:
      - net
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: vitrix-app-db
    restart: no
    networks:
      - net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=vitrix

networks:
  net:
    driver: bridge
    name: spring-boot-postgres-net
