version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: no
    ports:
      - "8081:8081"
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=1234
    networks:
      - net
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: vitrix-app-db
    restart: no
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=vitrix

volumes:
  db-data:

networks:
  net:
    driver: bridge
    name: spring-boot-postgres-net
