server:
  port: 8081

spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/vitrix
    username: root
    password: 11122006Wh
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod.filter.enabled: true
  servlet:
    multipart.max-file-size: 5MB
