server:
  port: 8081

spring:
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vitrix
    username: postgres
    password: 11122006Pl
  mvc:
    hiddenmethod.filter.enabled: true
  servlet:
    multipart.max-file-size: 5MB
  sql:
    init:
      mode: always
  flyway:
    user: postgres
    password: 11122006Pl

