CREATE TABLE images
(
    id           BIGINT       NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    file_name    VARCHAR(256) NOT NULL,
    file_size    BIGINT       NOT NULL,
    content_type VARCHAR(32)  NOT NULL,
    data         BYTEA        NOT NULL,
    created_at   TIMESTAMP,
    modified_at  TIMESTAMP
);

CREATE TABLE users
(
    id                BIGINT        NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    username          VARCHAR(64)   NOT NULL UNIQUE,
    password          VARCHAR(2048) NOT NULL,
    is_account_locked BOOLEAN       NOT NULL DEFAULT FALSE,
    role              VARCHAR(20)   NOT NULL,
    image_id          BIGINT,
    created_at        TIMESTAMP,
    modified_at       TIMESTAMP,

    CONSTRAINT fk_image_id FOREIGN KEY (image_id) REFERENCES images (id)
);

CREATE TABLE posts
(
    id          BIGINT      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(30) NOT NULL,
    image_id    BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL,
    created_at  TIMESTAMP,
    modified_at TIMESTAMP,

    CONSTRAINT fk_image_id FOREIGN KEY (image_id) REFERENCES images (id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

